### ISSUE TITLE
Account for possible extra padding after Index Table when reading a volume file

### ISSUE THREAD

**Issue by Brett208** [OutpostUniverse/OP2Utility#77] opened 2018-06-22 05:49 UTC
Some of the original volume files may have padding at the end of their Index Tables. This should probably be a medium priority bugfix?

**Comment by DanRStevens** [comment] 2018-06-22 06:54
Yes, agreed. We'll want to get this fixed reasonably soon.

Have you tested the code against the original VOL files shipped by Sierra? My guess is there may be some breakage.

**Comment by Brett208** [comment] 2018-06-25 07:01
Completed some testing on Sheets.vol from version 1.2.0.5.

There is space for 15 IndexEntries, but only 10 are used. Currently, space in the IndexEntries container is allocated for all 15 and the blank entries are just read in. Since This doesn't affect the final product since VolFile will not allow access to the indices past the m_NumberOfPackedFiles, which is properly calculated.

So currently, there is no bug. It might be smart to either limit reading IndexEntries to m_NumberOfPackedFiles. This would prevent reading in the empty IndexEntries.

**Comment by DanRStevens** [comment] 2018-06-25 09:57
Upon closer inspection of the code, there is no bug.
https://github.com/OutpostUniverse/OP2Utility/blob/682f6c24017417f3b2b0e13c0f2f1e23e044557d/Archives/VolFile.cpp#L388-L394

The VOLI section is the last section of the header, and hence also the last section which is read sequentially. Hence, padding at the end doesn't really matter. The only thing after it is the file data, and access to the file data is through random access seeking. Hence we don't need to explicitly read or skip over any padding here.

As for `m_NumberOfPackedFiles`, it is calculated by scanning the already read in data. I don't think there is anything that can or should be done there. It follows the way the game calculates the real end of the index table, so I think we want to keep it as is.

I'm closing this as not a bug.

**Closed by DanRStevens** 2018-06-25 09:57 UTC
